//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagementWebSite_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public long ApartmentId { get; set; }
        public string Number { get; set; }
        public long BuildingId { get; set; }
        public Nullable<long> TenantId { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> Bedrooms { get; set; }
        public Nullable<short> Bathrooms { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
