//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagementWebSite_V2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentId { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> ScheduleId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string Username { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
